### ISSUE TITLE
README could say a few words about loading frameless jar into notebook

### ISSUE THREAD

**Issue by phderome** [bmc/spark-frameless-talk-2018#1]
Some evidence found here and mentioning which artifact to use would help:

https://docs.databricks.com/user-guide/libraries.html#install-a-library-on-a-cluster

I think both 0.7 and 0.8 'should' work fine and I imagine we're still on Scala 2.11:
https://mvnrepository.com/artifact/org.typelevel/frameless-dataset_2.11/0.8.0

I tried both 0.7 and 0.8 on the cluster and got JVM runtime error for the first non-trivial Frameless command (59)
`val tds = TypedDataset.create(ds)`

```java.lang.VerifyError: class org.apache.spark.sql.FramelessInternals$DisambiguateRight overrides final method genCode.(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodegenContext;)Lorg/apache/spark/sql/catalyst/expressions/codegen/ExprCode;```

**Comment by phderome** [comment]
Brian updated the README recently and now it works (I also took the suggestion to use the precanned data he offers and mount it over dfs using my AWS S3 bucket as the generation of the data no longer seemed to work).

**Comment by TheBadEye** [comment]
What specifically did any one ever do 'not simply a README.md UPDATE from Brian' to resolve the 

val tds = TypedDataset.create(ds)

java.lang.VerifyError: class org.apache.spark.sql.FramelessInternals$DisambiguateRight overrides final method genCode.(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodegenContext;)Lorg/apache/spark/sql/catalyst/expressions/codegen/ExprCode;

**Comment by DCameronMauch** [comment]
I am also having this issue, but only when using DataBricks notebook.

**Comment by dsabanin** [comment]
I'm having the same problem with Databricks, so far no solution. Any clues?

**Comment by dsabanin** [comment]
If someone is having the same issues with frameless on Databricks, here's a change I've made to make it work:

https://github.com/dsabanin/frameless/commit/1ce8f0b8b44b070f7f00079d65ec2c2f5dc42786

I've not yet decided what's the best way to publish it for everyone, but if you want to test it out, you can just clone it, and run `sbt publishM2`, and it will push it to your local maven repository, where you can use it to compile your project.
